//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5448
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://jdcb.codeplex.com/RequestDef.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://jdcb.codeplex.com/RequestDef.xsd", IsNullable=false)]
public partial class root : object, System.ComponentModel.INotifyPropertyChanged {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DeleteRequest", typeof(rootDeleteRequest))]
    [System.Xml.Serialization.XmlElementAttribute("GetRequest", typeof(rootGetRequest))]
    [System.Xml.Serialization.XmlElementAttribute("MultiPartPostRequest", typeof(rootMultiPartPostRequest))]
    [System.Xml.Serialization.XmlElementAttribute("PostRequest", typeof(rootPostRequest))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
            this.RaisePropertyChanged("Item");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://jdcb.codeplex.com/RequestDef.xsd")]
public partial class rootDeleteRequest : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string commentField;
    
    private TemplateValueSet uRLTemplateField;
    
    private param[] queryField;
    
    private param[] headerField;
    
    /// <remarks/>
    public string Comment {
        get {
            return this.commentField;
        }
        set {
            this.commentField = value;
            this.RaisePropertyChanged("Comment");
        }
    }
    
    /// <remarks/>
    public TemplateValueSet URLTemplate {
        get {
            return this.uRLTemplateField;
        }
        set {
            this.uRLTemplateField = value;
            this.RaisePropertyChanged("URLTemplate");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public param[] Query {
        get {
            return this.queryField;
        }
        set {
            this.queryField = value;
            this.RaisePropertyChanged("Query");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public param[] Header {
        get {
            return this.headerField;
        }
        set {
            this.headerField = value;
            this.RaisePropertyChanged("Header");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jdcb.codeplex.com/RequestDef.xsd")]
public partial class TemplateValueSet : object, System.ComponentModel.INotifyPropertyChanged {
    
    private Template templateField;
    
    private paramForceSingle[] paramField;
    
    /// <remarks/>
    public Template Template {
        get {
            return this.templateField;
        }
        set {
            this.templateField = value;
            this.RaisePropertyChanged("Template");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("param")]
    public paramForceSingle[] param {
        get {
            return this.paramField;
        }
        set {
            this.paramField = value;
            this.RaisePropertyChanged("param");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jdcb.codeplex.com/RequestDef.xsd")]
public partial class Template : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string urlField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string url {
        get {
            return this.urlField;
        }
        set {
            this.urlField = value;
            this.RaisePropertyChanged("url");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jdcb.codeplex.com/RequestDef.xsd")]
public partial class param : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string commentField;
    
    private string[] textField;
    
    private paramType typeField;
    
    private string keyField;
    
    /// <remarks/>
    public string Comment {
        get {
            return this.commentField;
        }
        set {
            this.commentField = value;
            this.RaisePropertyChanged("Comment");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
            this.RaisePropertyChanged("Text");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public paramType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
            this.RaisePropertyChanged("type");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
            this.RaisePropertyChanged("key");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jdcb.codeplex.com/RequestDef.xsd")]
public enum paramType {
    
    /// <remarks/>
    Single,
    
    /// <remarks/>
    List,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jdcb.codeplex.com/RequestDef.xsd")]
public partial class paramForceSingle : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string commentField;
    
    private paramTypeForceSingle typeField;
    
    private string keyField;
    
    /// <remarks/>
    public string Comment {
        get {
            return this.commentField;
        }
        set {
            this.commentField = value;
            this.RaisePropertyChanged("Comment");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public paramTypeForceSingle type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
            this.RaisePropertyChanged("type");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
            this.RaisePropertyChanged("key");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jdcb.codeplex.com/RequestDef.xsd")]
public enum paramTypeForceSingle {
    
    /// <remarks/>
    Single,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://jdcb.codeplex.com/RequestDef.xsd")]
public partial class rootGetRequest : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string commentField;
    
    private TemplateValueSet uRLTemplateField;
    
    private param[] queryField;
    
    private param[] headerField;
    
    /// <remarks/>
    public string Comment {
        get {
            return this.commentField;
        }
        set {
            this.commentField = value;
            this.RaisePropertyChanged("Comment");
        }
    }
    
    /// <remarks/>
    public TemplateValueSet URLTemplate {
        get {
            return this.uRLTemplateField;
        }
        set {
            this.uRLTemplateField = value;
            this.RaisePropertyChanged("URLTemplate");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public param[] Query {
        get {
            return this.queryField;
        }
        set {
            this.queryField = value;
            this.RaisePropertyChanged("Query");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public param[] Header {
        get {
            return this.headerField;
        }
        set {
            this.headerField = value;
            this.RaisePropertyChanged("Header");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://jdcb.codeplex.com/RequestDef.xsd")]
public partial class rootMultiPartPostRequest : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string commentField;
    
    private TemplateValueSet uRLTemplateField;
    
    private param[] queryField;
    
    private param[] headerField;
    
    private param[] postField;
    
    private paramForceSingle[] fileField;
    
    /// <remarks/>
    public string Comment {
        get {
            return this.commentField;
        }
        set {
            this.commentField = value;
            this.RaisePropertyChanged("Comment");
        }
    }
    
    /// <remarks/>
    public TemplateValueSet URLTemplate {
        get {
            return this.uRLTemplateField;
        }
        set {
            this.uRLTemplateField = value;
            this.RaisePropertyChanged("URLTemplate");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public param[] Query {
        get {
            return this.queryField;
        }
        set {
            this.queryField = value;
            this.RaisePropertyChanged("Query");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public param[] Header {
        get {
            return this.headerField;
        }
        set {
            this.headerField = value;
            this.RaisePropertyChanged("Header");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public param[] Post {
        get {
            return this.postField;
        }
        set {
            this.postField = value;
            this.RaisePropertyChanged("Post");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("param", IsNullable=false)]
    public paramForceSingle[] File {
        get {
            return this.fileField;
        }
        set {
            this.fileField = value;
            this.RaisePropertyChanged("File");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://jdcb.codeplex.com/RequestDef.xsd")]
public partial class rootPostRequest : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string commentField;
    
    private TemplateValueSet uRLTemplateField;
    
    private param[] queryField;
    
    private param[] headerField;
    
    private param[] postField;
    
    /// <remarks/>
    public string Comment {
        get {
            return this.commentField;
        }
        set {
            this.commentField = value;
            this.RaisePropertyChanged("Comment");
        }
    }
    
    /// <remarks/>
    public TemplateValueSet URLTemplate {
        get {
            return this.uRLTemplateField;
        }
        set {
            this.uRLTemplateField = value;
            this.RaisePropertyChanged("URLTemplate");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public param[] Query {
        get {
            return this.queryField;
        }
        set {
            this.queryField = value;
            this.RaisePropertyChanged("Query");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public param[] Header {
        get {
            return this.headerField;
        }
        set {
            this.headerField = value;
            this.RaisePropertyChanged("Header");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public param[] Post {
        get {
            return this.postField;
        }
        set {
            this.postField = value;
            this.RaisePropertyChanged("Post");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}
